import type { TNodeDefinition } from '../_types/node.type';

export const NODE_CATALOG: TNodeDefinition[] = [
	{
		key: 'input.ask',
		category: 'input',
		label: 'Ask Input',
		description: 'Prompt for text when the workflow runs.',
		icon: 'Q',
		color: 'sky',
		inputs: [],
		outputs: [{ id: 'value', name: 'value', type: 'string' }],
		fields: [
			{
				key: 'label',
				label: 'Question',
				kind: 'text',
				default: 'What should we process?',
				help: 'The text prompt shown to users when the workflow runs.',
			},
			{
				key: 'required',
				label: 'Required',
				kind: 'toggle',
				default: true,
				help: 'Whether the user must provide a value before continuing.',
			},
		],
	},
	{
		key: 'input.file',
		category: 'input',
		label: 'File Input',
		description: 'Accept a CSV, PDF, image, or other file.',
		icon: 'F',
		color: 'sky',
		inputs: [],
		outputs: [{ id: 'file', name: 'file', type: 'file' }],
		fields: [
			{
				key: 'accept',
				label: 'Accepted types',
				kind: 'text',
				default: '.pdf,.csv,image/*',
				help: 'File extensions or MIME types (e.g., .pdf,.csv,image/*).',
			},
		],
	},
	{
		key: 'ai.chat',
		category: 'ai',
		label: 'Ask AI',
		description: 'Run a single LLM prompt over the incoming context.',
		icon: 'AI',
		color: 'violet',
		inputs: [{ id: 'in', name: 'context', type: 'any' }],
		outputs: [{ id: 'out', name: 'response', type: 'string' }],
		fields: [
			{
				key: 'model',
				label: 'Model',
				kind: 'model',
				default: 'gpt-4o-mini',
				help: 'Select the AI model to use for this request.',
				options: [
					{ label: 'GPT-4o mini', value: 'gpt-4o-mini' },
					{ label: 'GPT-4o', value: 'gpt-4o' },
					{ label: 'Claude Sonnet', value: 'claude-sonnet' },
					{ label: 'Gemini Pro', value: 'gemini-pro' },
				],
			},
			{
				key: 'prompt',
				label: 'Prompt',
				kind: 'longtext',
				rows: 6,
				required: true,
				supportsVariables: true,
				help: 'Write your prompt here. Use {{variable}} syntax to inject values from previous nodes.',
				placeholder: 'Use {{Ask Input.value}} and return a concise answer.',
			},
			{
				key: 'temperature',
				label: 'Temperature',
				kind: 'number',
				default: 0.4,
				help: 'Controls randomness: lower = more deterministic, higher = more creative.',
			},
		],
	},
	{
		key: 'ai.extract',
		category: 'extract',
		label: 'Extract Data',
		description: 'Extract structured JSON using a schema.',
		icon: '{}',
		color: 'fuchsia',
		inputs: [{ id: 'text', name: 'text', type: 'string' }],
		outputs: [{ id: 'data', name: 'data', type: 'json' }],
		fields: [
			{
				key: 'schema',
				label: 'Schema',
				kind: 'code',
				rows: 7,
				required: true,
				help: 'JSON schema describing the structure to extract (e.g., {"name": "string", "value": "number"}).',
			},
			{
				key: 'model',
				label: 'Model',
				kind: 'model',
				default: 'gpt-4o-mini',
				help: 'AI model for extracting structured data.',
			},
		],
	},
	{
		key: 'scrape.url',
		category: 'scrape',
		label: 'Website Scraper',
		description: 'Fetch a page and return clean markdown.',
		icon: 'W',
		color: 'emerald',
		inputs: [{ id: 'url', name: 'url', type: 'string' }],
		outputs: [{ id: 'content', name: 'content', type: 'string' }],
		fields: [
			{
				key: 'url',
				label: 'URL',
				kind: 'text',
				required: true,
				supportsVariables: true,
				help: 'Enter the full URL to scrape. Variables like {{Ask Input.value}} are supported.',
			},
			{
				key: 'waitFor',
				label: 'Wait for selector',
				kind: 'text',
				help: 'Optional CSS selector to wait for before extracting content.',
			},
		],
	},
	{
		key: 'data.http',
		category: 'data',
		label: 'HTTP Request',
		description: 'Call a REST endpoint and return JSON.',
		icon: 'API',
		color: 'amber',
		inputs: [{ id: 'body', name: 'body', type: 'any' }],
		outputs: [{ id: 'response', name: 'response', type: 'json' }],
		fields: [
			{
				key: 'method',
				label: 'Method',
				kind: 'select',
				default: 'GET',
				help: 'HTTP method for the request.',
				options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map((method) => ({
					label: method,
					value: method,
				})),
			},
			{
				key: 'url',
				label: 'URL',
				kind: 'text',
				required: true,
				supportsVariables: true,
				help: 'Request URL. Variables like {{Ask Input.value}} are supported.',
			},
			{
				key: 'headers',
				label: 'Headers',
				kind: 'kv',
				help: 'Key-value pairs for request headers.',
			},
			{
				key: 'body',
				label: 'Body',
				kind: 'code',
				rows: 5,
				help: 'Request body as JSON. Use for POST/PUT requests.',
			},
		],
	},
	{
		key: 'logic.if',
		category: 'logic',
		label: 'If / Else',
		description: 'Branch based on a boolean expression.',
		icon: 'IF',
		color: 'rose',
		inputs: [{ id: 'in', name: 'value', type: 'any' }],
		outputs: [
			{ id: 'true', name: 'true', type: 'any' },
			{ id: 'false', name: 'false', type: 'any' },
		],
		fields: [
			{
				key: 'expression',
				label: 'Condition',
				kind: 'text',
				required: true,
				help: 'JavaScript expression to evaluate (e.g., value > 10).',
			},
		],
	},
	{
		key: 'loop.each',
		category: 'loop',
		label: 'Loop List',
		description: 'Iterate over every item in a list.',
		icon: 'LO',
		color: 'indigo',
		inputs: [{ id: 'items', name: 'items', type: 'list' }],
		outputs: [{ id: 'item', name: 'item', type: 'any' }],
		fields: [
			{
				key: 'concurrency',
				label: 'Concurrency',
				kind: 'number',
				default: 5,
				help: 'Number of items to process simultaneously.',
			},
		],
		supportsLoopMode: true,
	},
	{
		key: 'int.slack',
		category: 'integration',
		label: 'Send Slack',
		description: 'Send a message to a Slack channel.',
		icon: 'SL',
		color: 'cyan',
		inputs: [{ id: 'message', name: 'message', type: 'string' }],
		outputs: [{ id: 'sent', name: 'sent', type: 'boolean' }],
		fields: [
			{
				key: 'credential',
				label: 'Credential',
				kind: 'credential',
				required: true,
				help: 'Select a connected Slack credential for authentication.',
			},
			{
				key: 'channel',
				label: 'Channel',
				kind: 'text',
				required: true,
				help: 'Slack channel name (e.g., #general or @username for DMs).',
			},
			{
				key: 'message',
				label: 'Message',
				kind: 'longtext',
				supportsVariables: true,
				help: 'Message content. Supports markdown and {{variable}} syntax.',
			},
		],
		requiresCredential: true,
	},
	{
		key: 'output.display',
		category: 'output',
		label: 'Output',
		description: 'Return a final workflow result.',
		icon: 'OUT',
		color: 'green',
		inputs: [{ id: 'value', name: 'value', type: 'any' }],
		outputs: [],
		fields: [
			{
				key: 'name',
				label: 'Output name',
				kind: 'text',
				default: 'result',
				help: 'Programmatic name for this output in your workflow.',
			},
			{
				key: 'type',
				label: 'Type',
				kind: 'select',
				default: 'any',
				help: 'Data type for the output value.',
				options: [
					{ label: 'Text', value: 'string' },
					{ label: 'List', value: 'list' },
					{ label: 'JSON', value: 'json' },
					{ label: 'Any', value: 'any' },
				],
			},
		],
	},
	{
		key: 'note.sticky',
		category: 'note',
		label: 'Sticky Note',
		description: 'Document assumptions and instructions on the canvas.',
		icon: 'N',
		color: 'zinc',
		inputs: [],
		outputs: [],
		fields: [
			{
				key: 'content',
				label: 'Note',
				kind: 'longtext',
				rows: 5,
				help: 'Add documentation directly on your workflow canvas.',
			},
		],
	},
];

export const NODE_CATALOG_MAP = Object.fromEntries(
	NODE_CATALOG.map((node) => [node.key, node]),
) as Record<string, TNodeDefinition>;

export const getNodeDefinition = (
	defKey: string,
	runtimeDefinition?: TNodeDefinition,
): TNodeDefinition | undefined => runtimeDefinition ?? NODE_CATALOG_MAP[defKey];
